version: "3.9"
services:
  db:
    image: postgres:12.1
    container_name: postgreSQL
    ports:
      - 5432:5432
    hostname: postgreSQL
    env_file:
      - .env
    volumes:
      - postgreSQLDATA:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      alexvirtualbr:
        ipv4_address: 172.16.250.10
  web:
    build: .
    container_name: webApp
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/alexvirtualbrApp:rw
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db  
    env_file:
      - .env
    networks: 
      alexvirtualbr:
        ipv4_address: 172.16.250.11
networks: 
  alexvirtualbr:
    driver: bridge    
    ipam:
      driver: default
      config:
        - subnet: 172.16.250.0/24
volumes:
  postgreSQLDATA:
    driver: local
  gem_cache:
  db_data:
  node_modules: 