FROM ruby:3.1
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
WORKDIR /alexvirtualbrApp
COPY Gemfile /alexvirtualbrApp/Gemfile
COPY Gemfile.lock /alexvirtualbrApp/Gemfile.lock
RUN bundle install 
COPY . /alexvirtualbrApp
COPY entrypoint.sh /usr/bin
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "s", "-b, "0.0.0.0"]